name: run_script_with_delay
on:
  workflow_dispatch:
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: ./workflow_scripts/script_with_delay.sh
